# Generated by Django 5.1.2 on 2025-08-01 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_insercao', models.DateField()),
                ('hora', models.TimeField()),
                ('numero_equipamento', models.CharField(max_length=100)),
                ('setor_insercao', models.CharField(max_length=50)),
                ('numero_carga', models.CharField(max_length=100)),
                ('cliente', models.CharField(default='PRYSMIAN', max_length=100)),
                ('origem', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('transportadora', models.CharField(max_length=100)),
                ('placa', models.CharField(max_length=20)),
                ('agente', models.CharField(max_length=50)),
                ('valor_carga', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
    ]
