# Generated by Django 5.1.2 on 2025-08-01 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carga',
            name='observacao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
