# Generated by Django 5.1.2 on 2025-08-01 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0002_carga_observacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='carga',
            name='carga_no_chao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='carga',
            name='golden_ok',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='carga',
            name='grupo_operativo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='carga',
            name='krona_ok',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='carga',
            name='modalidade_carga',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
