# Generated by Django 5.1.2 on 2025-08-01 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0003_carga_carga_no_chao_carga_golden_ok_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carga',
            name='carga_no_chao',
            field=models.CharField(max_length=50),
        ),
    ]
