# Generated by Django 5.2.4 on 2025-09-17 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0004_alter_carga_carga_no_chao'),
    ]

    operations = [
        migrations.AddField(
            model_name='carga',
            name='contrato',
            field=models.CharField(choices=[('Retornável', 'Retornável'), ('Descartável', 'Descartável')], default='Retornável', max_length=20),
        ),
    ]
