# Generated by Django 5.2.4 on 2025-09-19 00:32

from django.db import migrations


def update_contrato_to_na(apps, schema_editor):
    Carga = apps.get_model('registros', 'Carga')
    # Atualiza todos os registros que têm 'Retornável' para 'N/A'
    Carga.objects.filter(contrato='Retornável').update(contrato='N/A')


def reverse_update_contrato(apps, schema_editor):
    Carga = apps.get_model('registros', 'Carga')
    # Reverte: atualiza todos os registros que têm 'N/A' para 'Retornável'
    Carga.objects.filter(contrato='N/A').update(contrato='Retornável')


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0005_carga_contrato'),
    ]

    operations = [
        migrations.RunPython(update_contrato_to_na, reverse_update_contrato),
    ]
