# Generated by Django 5.1.2 on 2025-09-01 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CostaRica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_insercion', models.DateField(verbose_name='Fecha de la inserción')),
                ('hora', models.TimeField(verbose_name='Hora')),
                ('sector', models.CharField(max_length=100, verbose_name='Sector')),
                ('transportadora', models.CharField(max_length=100, verbose_name='Transportadora')),
                ('placa_tracto', models.CharField(max_length=20, verbose_name='Placa tracto')),
                ('placa_remolque', models.CharField(max_length=20, verbose_name='Placa remolque')),
                ('cliente', models.CharField(max_length=100, verbose_name='Cliente')),
                ('origen', models.CharField(max_length=100, verbose_name='Origen')),
                ('destino', models.CharField(max_length=100, verbose_name='Destino')),
                ('id_localizador', models.CharField(max_length=100, verbose_name='ID localizador')),
                ('valor_carga', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor carga')),
                ('carga_en_piso', models.CharField(max_length=100, verbose_name='Carga en el piso')),
                ('oficial', models.CharField(max_length=100, verbose_name='Oficial')),
            ],
            options={
                'verbose_name': 'Costa Rica',
                'verbose_name_plural': 'Costa Rica',
            },
        ),
    ]
