# Generated by Django 5.2.4 on 2025-09-17 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costa_rica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='costarica',
            name='contrato',
            field=models.CharField(choices=[('Retornável', 'Retornável'), ('Descartável', 'Descartável')], default='Retornável', max_length=20, verbose_name='Contrato'),
        ),
    ]
