# Generated by Django 5.2.4 on 2025-09-17 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costa_rica', '0002_costarica_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='costarica',
            name='observacao',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Observación'),
        ),
    ]
