# Generated by Django 5.2.4 on 2025-09-19 00:31

from django.db import migrations


def update_contrato_to_na(apps, schema_editor):
    CostaRica = apps.get_model('costa_rica', 'CostaRica')
    # Atualiza todos os registros que têm 'Retornable' para 'N/A'
    CostaRica.objects.filter(contrato='Retornable').update(contrato='N/A')


def reverse_update_contrato(apps, schema_editor):
    CostaRica = apps.get_model('costa_rica', 'CostaRica')
    # Reverte: atualiza todos os registros que têm 'N/A' para 'Retornable'
    CostaRica.objects.filter(contrato='N/A').update(contrato='Retornable')


class Migration(migrations.Migration):

    dependencies = [
        ('costa_rica', '0003_costarica_observacao'),
    ]

    operations = [
        migrations.RunPython(update_contrato_to_na, reverse_update_contrato),
    ]
