# Generated by Django 5.1.2 on 2025-09-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mexico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mexico',
            name='carga_en_piso',
            field=models.CharField(max_length=100, verbose_name='Carga en el piso'),
        ),
    ]
