# Generated by Django 5.2.4 on 2025-09-17 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mexico', '0002_alter_mexico_carga_en_piso'),
    ]

    operations = [
        migrations.AddField(
            model_name='mexico',
            name='contrato',
            field=models.CharField(choices=[('Retornável', 'Retornável'), ('Descartável', 'Descartável')], default='Retornável', max_length=20, verbose_name='Contrato'),
        ),
    ]
