# Generated by Django 5.2.4 on 2025-09-19 00:32

from django.db import migrations


def update_contrato_to_na(apps, schema_editor):
    Mexico = apps.get_model('mexico', 'Mexico')
    # Atualiza todos os registros que têm 'Retornable' para 'N/A'
    Mexico.objects.filter(contrato='Retornable').update(contrato='N/A')


def reverse_update_contrato(apps, schema_editor):
    Mexico = apps.get_model('mexico', 'Mexico')
    # Reverte: atualiza todos os registros que têm 'N/A' para 'Retornable'
    Mexico.objects.filter(contrato='N/A').update(contrato='Retornable')


class Migration(migrations.Migration):

    dependencies = [
        ('mexico', '0004_mexico_observacao'),
    ]

    operations = [
        migrations.RunPython(update_contrato_to_na, reverse_update_contrato),
    ]
