# Generated by Django 5.1.2 on 2025-08-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('numero_equipamento', models.CharField(max_length=100)),
                ('setor_insercao', models.CharField(max_length=100)),
                ('modalidade', models.CharField(max_length=100)),
                ('cliente', models.CharField(max_length=100)),
                ('origem', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('transportadora', models.CharField(max_length=100)),
                ('placa', models.CharField(max_length=20)),
                ('agente', models.CharField(max_length=100)),
                ('carga_no_chao', models.BooleanField(default=False)),
                ('valor_carga', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
