# Generated by Django 5.1.2 on 2025-08-01 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sed',
            name='carga_no_chao',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False),
        ),
    ]
