# Generated by Django 5.2.4 on 2025-09-17 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sed', '0002_alter_sed_carga_no_chao'),
    ]

    operations = [
        migrations.AddField(
            model_name='sed',
            name='contrato',
            field=models.CharField(choices=[('Retornável', 'Retornável'), ('Descartável', 'Descartável')], default='Retornável', max_length=20),
        ),
    ]
