# Generated by Django 5.2.4 on 2025-09-17 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sed', '0003_sed_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='sed',
            name='observacao',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Observação'),
        ),
    ]
